# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd

from ..aerosol1d import Aerosol1D
from ..aerosol2d import Aerosol2D
from .Common import detect_delimiter


def Load_OPCN3_file(file: str, extra_data: bool = False, PM_focus: bool = False):
    """
    Load data from an OPS (Optical Particle Sizer) file and route to the appropriate parser.

    This function inspects the file header and determines whether the file was exported
    via the AIM software or directly from the instrument. Based on this, it dispatches
    to the correct loader: `Load_OPS_AIM` or `Load_OPS_Direct`.

    Parameters
    ----------
    file : str
        Path to the OPS data file.
    extra_data : bool, optional
        If True, attaches unused columns to the returned object as `._extra_data`.
        Passed directly to the underlying loader. Default is False.

    Returns
    -------
    OPS : Aerosol2D
        A class containing size-resolved particle data and instrument metadata.

    Raises
    ------
    Exception
        If the file type cannot be identified from the header.

    Notes
    -----
    - This function depends on `Com.detect_delimiter()` and assumes either AIM-exported
      or direct instrument export file formats.
    - If new formats are introduced, this function should be updated accordingly.
    """
    encoding, delimiter = detect_delimiter(file)

    # Peek at the first line to determine file type
    first_line = np.genfromtxt(
        file,
        delimiter=delimiter,
        encoding=encoding,
        skip_header=0,
        max_rows=1,
        dtype=str,
    )

    if len(first_line)<=34:
        if PM_focus:
            return Load_OPCN3_file_PM_old(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
        else:
            return Load_OPCN3_file_old(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
    elif first_line[-1] == "OPC":
        if PM_focus:
            return Load_OPCN3_file_PM_new(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
        else:
            return Load_OPCN3_file_new(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
    else:
        raise Exception("Unrecognized OPS file format. Unable to parse.")

###############################################################################


def Load_OPCN3_file_old(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> Aerosol2D:


    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.

    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : Aerosol2D
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including bin edges, serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")
        
    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"date": "Datetime"}, inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%dT%H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]
    bin_edges = (
        np.array([float(col.split("Bin")[1]) for col in bin_cols] + [40.0]) * 1000
    )  # in nm
    bin_mids = (bin_edges[:-1] + bin_edges[1:]) / 2

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temperature.C": "Temp (C)", "RH.p": "RH (%)"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df.drop(columns=bin_cols)

        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    bin_df = pd.DataFrame(concentrations, columns=bin_mids.astype(str))

    final_df = pd.concat([df["Datetime"], total_df, bin_df], axis=1)

    OPCN = Aerosol2D(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "bin_edges": bin_edges,
        "bin_mids": bin_mids,
        "density": 1.65,
        "serial_number": "unknown",
        "unit": "cm⁻³",
        "dtype": "dN",
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN

###############################################################################


def Load_OPCN3_file_new(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> Aerosol2D:
    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.

    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : Aerosol2D
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including bin edges, serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")

    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"Date": "Datetime"}, inplace=True)
    df.drop(columns='OPC',inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%d %H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]
    bin_edges = (
        np.array([0.35,0.46,0.66,1.0,1.3,1.7,2.3,3.0,4.0,5.2,6.5,8.0,10.0,12.0,
                 14.0,16.0,18.0,20.0,22.0,25.0,28.0,31.0,34.0,37.0,40.0]) * 1000
    )  # in nm
    bin_mids = (bin_edges[:-1] + bin_edges[1:]) / 2

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temp": "Temp (C)", "RH": "RH (%)",
                 "PM1": "PM1(ug/m3)", "PM2.5": "PM2.5(ug/m3)",
                 "PM10": "PM10(ug/m3)"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df.drop(columns=bin_cols)
        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    bin_df = pd.DataFrame(concentrations, columns=bin_mids.astype(str))

    final_df = pd.concat([df["Datetime"], total_df, bin_df], axis=1)

    OPCN = Aerosol2D(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "bin_edges": bin_edges,
        "bin_mids": bin_mids,
        "density": 1.65,
        "serial_number": "unknown",
        "unit": "cm⁻³",
        "dtype": "dN",
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN

#%%%
from io import StringIO
from datetime import datetime, timedelta

import pathlib
import pandas as pd
import requests
import functools

PATH_ROOT = pathlib.Path(__file__).parent

COLUMNS_OPCN3 = [
    "bin0",
    "bin1",
    "bin2",
    "bin3",
    "bin4",
    "bin5",
    "bin6",
    "bin7",
    "bin8",
    "bin9",
    "bin10",
    "bin11",
    "bin12",
    "bin13",
    "bin14",
    "bin15",
    "bin16",
    "bin17",
    "bin18",
    "bin19",
    "bin20",
    "bin21",
    "bin22",
    "bin23",
    "MTof_bin1",
    "MTof_bin3",
    "MTof_bin5",
    "MTof_bin7",
    "period",
    "flowrate",
    "temperature",
    "relative_humidity",
    "pm1",
    "pm2.5",
    "pm10",
    "checksum",
]


def get_api_sensor_data_column(
    guid: str,
    from_date: str,
    to_date: str,
    column: str,
    segment: int,
    print_progress: bool = True,
) -> pd.DataFrame:
    """
    Get sensor data from a device given its GUID and other parameters.

    Parameters:
    guid (str): The GUID of the device.
    from_date (str): Start date for data retrieval. Format: YYYY-MM-DDT00:00:00.000Z.
    to_date (str): End date for data retrieval. Format: YYYY-MM-DDT00:00:00.000Z.
    column (str): Column to read.
    segment (int): Number of hours to segment the time period.
    print_progress (bool): If True, progress messages will be printed.

    Returns:
    pd.DataFrame: Dataframe containing the sensor data.
    """
    # API URL
    yoda_url = "https://yoda.localdom.net:8443/organization/c085/dataopsamling/device-manager-data-get/"

    # Convert the date strings to datetime objects
    start = datetime.strptime(from_date, "%Y-%m-%dT%H:%M:%S.%fZ")
    end = datetime.strptime(to_date, "%Y-%m-%dT%H:%M:%S.%fZ")

    # Calculate the total duration in hours
    total_hours = int((end - start).total_seconds() // 3600)

    # Create a list of timestamps at segment hour intervals
    if total_hours < segment:
        date_list = [date.strftime("%Y-%m-%dT%H:%M:%S.%fZ") for date in [start, end]]
    else:
        date_list = [
            (start + timedelta(hours=segment * x)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
            for x in range(total_hours // segment + 1)
        ]

    data_frame = pd.DataFrame()  # Data frame to fill

    for n in range(len(date_list) - 1):
        parameters = {
            "guid": guid,
            "columns": column,
            "fromdate": date_list[n],
            "todate": date_list[n + 1],
        }

        r = requests.get(yoda_url, params=parameters, verify=False)
        print(r.url)
        response = r.content
        response_string = response.decode("utf-8")

        if "Something went wrong" in response_string:
            if print_progress:
                print(
                    f"Request: {n + 1}/{len(date_list) - 1} | {response_string} | for period starting at: {date_list[n]}"
                )
            continue
        else:
            sensor_csv = StringIO(response_string)
            sensor_data = pd.read_csv(sensor_csv)

            if sensor_data.empty:
                if print_progress:
                    print(
                        f"Request: {n + 1}/{len(date_list) - 1} | No data in period starting at: {date_list[n]}"
                    )
            else:
                data_frame = pd.concat([data_frame, sensor_data], ignore_index=True)
                if print_progress:
                    print(f"Request: {n + 1}/{len(date_list) - 1} | Success!")

    return data_frame


def get_api_sensor_data(
    guid: str,
    from_date: str,
    to_date: str,
    columns: list[str],
    segment: int,
    print_progress: bool = True,
) -> pd.DataFrame:
    """
    Get sensor data from a device given its GUID and other parameters.

    Parameters:
    guid (str): The GUID of the device.
    from_date (str): Start date for data retrieval. Format: YYYY-MM-DDT00:00:00.000Z.
    to_date (str): End date for data retrieval. Format: YYYY-MM-DDT00:00:00.000Z.
    columns (list[str]): Columns to read; each column is read one at a time.
    segment (int): Number of hours to segment the time period.
    print_progress (bool): If True, progress messages will be printed.

    Returns:
    pd.DataFrame: Dataframe containing the sensor data.
    """
    frames = map(
        lambda c: get_api_sensor_data_column(
            guid, from_date, to_date, c, segment, print_progress
        ),
        columns,
    )
    init_frame = next(frames)
    return functools.reduce(lambda acc, el: acc.merge(el), frames, init_frame)


def get_opcn3_data(guid, date) -> pd.DataFrame:
    return get_api_sensor_data(
        guid, date + "T00:08:00.000Z", date + "T15:59:59.999Z", COLUMNS_OPCN3, 25, True
    )


def save_isover_data_to_disk():
    get_opcn3_data("4e68390b73df4bc88bf877336e9e8a3b", "2024-06-24").to_csv(
        PATH_ROOT / "05 Isover" / "Kalibrering" / "am-sensor_1.csv"
    )
    get_opcn3_data("65e10218df1249c1a4e07e565d3ccec2", "2024-06-24").to_csv(
        PATH_ROOT / "05 Isover" / "Kalibrering" / "am-sensor_2.csv"
    )


def save_skylight_data_to_disk():
    get_opcn3_data("bf750d3873e1413cb868d1dea3f608ed", "2024-06-24").to_csv(
        PATH_ROOT / "06 SkyLight" / "Kalibrering" / "am-sensor_3.csv"
    )
    get_opcn3_data("4cb49e550d5c45989d23f3ebbb553010", "2024-06-24").to_csv(
        PATH_ROOT / "06 SkyLight" / "Kalibrering" / "am-sensor_4.csv"
    )


def save_grundfos_data_to_disk():
    get_opcn3_data("a944c08aff6c4fa68f0a6fb5fe8e7789", "2024-06-17").to_csv(
        PATH_ROOT / "04 Grundfos" / "Kalibrering" / "am-sensor_5.csv"
    )
    get_opcn3_data("c6f98249001540f1a6a594d10784ce23", "2024-06-17").to_csv(
        PATH_ROOT / "04 Grundfos" / "Kalibrering" / "am-sensor_6.csv"
    )


def save_kingo_data_to_disk():
    get_opcn3_data("993820730cf4497781038f50badb2391", "2024-05-27").to_csv(
        PATH_ROOT / "03 Kingo" / "Kalibrering" / "am-sensor_7.csv"
    )
    get_opcn3_data("b43adfacc63345c69fe067c465d897ac", "2024-05-27").to_csv(
        PATH_ROOT / "03 Kingo" / "Kalibrering" / "am-sensor_8.csv"
    )


def save_kingo_data_to_disk_20241111():
    get_opcn3_data("993820730cf4497781038f50badb2391", "2024-11-11").to_csv(
        PATH_ROOT / "03 Kingo" / "Kalibrering" / "20241111" / "am-sensor_7.csv"
    )
    get_opcn3_data("b43adfacc63345c69fe067c465d897ac", "2024-11-11").to_csv(
        PATH_ROOT / "03 Kingo" / "Kalibrering" / "20241111" / "am-sensor_8.csv"
    )


if __name__ == "__main__":
    # save_isover_data_to_disk()
    # save_skylight_data_to_disk()
    # save_grundfos_data_to_disk()
    # save_kingo_data_to_disk()
    save_kingo_data_to_disk_20241111()


#%%


def Load_OPCN3_file_PM_old(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> Aerosol1D:


    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.
    Simpler version, that only returns total concentration and PM1, 2.5 and 10.
    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : Aerosol1D
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including bin edges, serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")
        
    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"date": "Datetime"}, inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%dT%H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temperature.C": "Temp (C)", "RH.p": "RH (%)",
                 "PM1(ug/m3)": "PM1", "PM2.5(ug/m3)": "PM2.5",
                 "PM10(ug/m3)": "PM10"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df[['Datetime','Temp (C)','RH (%)',"Period (s)"]]

        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    PM_df = df[['PM1','PM2.5','PM10']]

    final_df = pd.concat([df["Datetime"], total_df, PM_df], axis=1)

    OPCN = Aerosol1D(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "density": 1.65,
        "serial_number": "unknown",
        "unit": {"Total_conc": "cm⁻³", "PM": "ug/m³"},
        "dtype": {"Total_conc": "dN", "PM": "dM"},
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN

###############################################################################


def Load_OPCN3_file_PM_new(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> Aerosol1D:
    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.
    Simpler version, that only returns total concentration and PM1, 2.5 and 10.
    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : Aerosol1D
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including bin edges, serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")

    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"Date": "Datetime"}, inplace=True)
    df.drop(columns='OPC',inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%d %H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temp": "Temp (C)", "RH": "RH (%)"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df[['Datetime','Temp (C)','RH (%)',"Period (s)"]]
        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    PM_df = df[['PM1','PM2.5','PM10']]
                        
    final_df = pd.concat([df["Datetime"], total_df, PM_df], axis=1)

    OPCN = Aerosol1D(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "density": 1.65,
        "serial_number": "unknown",
        "unit": {"Total_conc": "cm⁻³", "PM": "ug/m³"},
        "dtype": {"Total_conc": "dN", "PM": "dM"},
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN