# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd

from ..aerosol1d import Aerosol1D
from ..aerosol2d import Aerosol2D
from ..aerosolalt import AerosolAlt
from .Common import detect_delimiter


def Load_OPCN3_file(file: str, extra_data: bool = False, PM_focus: bool = False):
    """
    Load data from an OPC-N3 particle sensor file and route to the appropriate parser.

    This function inspects the file header and determines whether the file was exported
    via the AIM software or directly from the instrument. Based on this, it dispatches
    to the correct loader: `Load_OPS_AIM` or `Load_OPS_Direct`.

    Parameters
    ----------
    file : str
        Path to the OPS data file.
    extra_data : bool, optional
        If True, attaches unused columns to the returned object as `._extra_data`.
        Passed directly to the underlying loader. Default is False.
    PM_focus : bool, optional
        If True the data focuses only on the PM data and ignoring the size-resolved information.
        Instead returns a AerosolAlt with 'Total_conc', 'PM1', 'PM2.5', 'PM10'.
        Default is False.

    Returns
    -------
    OPC : Aerosol2D/AerosolAlt
        A class containing size-resolved particle data and instrument metadata.
        Or a class containing 

    Raises
    ------
    Exception
        If the file type cannot be identified from the header.

    Notes
    -----
    - This function depends on `Com.detect_delimiter()` and assumes either AIM-exported
      or direct instrument export file formats.
    - If new formats are introduced, this function should be updated accordingly.
    """
    encoding, delimiter = detect_delimiter(file)

    # Peek at the first line to determine file type
    first_line = np.genfromtxt(
        file,
        delimiter=delimiter,
        encoding=encoding,
        skip_header=0,
        max_rows=1,
        dtype=str,
    )

    if len(first_line)<=34:
        if PM_focus:
            return Load_OPCN3_file_PM_old(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
        else:
            return Load_OPCN3_file_old(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
    elif first_line[-1] == "OPC":
        if PM_focus:
            return Load_OPCN3_file_PM_new(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
        else:
            return Load_OPCN3_file_new(
                file, extra_data=extra_data, encoding=encoding, delimiter=delimiter
            )
    else:
        raise Exception("Unrecognized OPS file format. Unable to parse.")

###############################################################################


def Load_OPCN3_file_old(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> Aerosol2D:


    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.

    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : Aerosol2D
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including bin edges, serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")
        
    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"date": "Datetime"}, inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%dT%H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]
    bin_edges = (
        np.array([float(col.split("Bin")[1]) for col in bin_cols] + [40.0]) * 1000
    )  # in nm
    bin_mids = (bin_edges[:-1] + bin_edges[1:]) / 2

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temperature.C": "Temp (C)", "RH.p": "RH (%)"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df.drop(columns=bin_cols)

        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    bin_df = pd.DataFrame(concentrations, columns=bin_mids.astype(str))

    final_df = pd.concat([df["Datetime"], total_df, bin_df], axis=1)

    OPCN = Aerosol2D(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "bin_edges": bin_edges,
        "bin_mids": bin_mids,
        "density": 1.65,
        "serial_number": "unknown",
        "unit": "cm⁻³",
        "dtype": "dN",
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN

###############################################################################


def Load_OPCN3_file_new(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> Aerosol2D:
    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.

    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : Aerosol2D
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including bin edges, serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")

    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"Date": "Datetime"}, inplace=True)
    df.drop(columns='OPC',inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%d %H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]
    bin_edges = (
        np.array([0.35,0.46,0.66,1.0,1.3,1.7,2.3,3.0,4.0,5.2,6.5,8.0,10.0,12.0,
                 14.0,16.0,18.0,20.0,22.0,25.0,28.0,31.0,34.0,37.0,40.0]) * 1000
    )  # in nm
    bin_mids = (bin_edges[:-1] + bin_edges[1:]) / 2

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temp": "Temp (C)", "RH": "RH (%)",
                 "PM1": "PM1(ug/m3)", "PM2.5": "PM2.5(ug/m3)",
                 "PM10": "PM10(ug/m3)"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df.drop(columns=bin_cols)
        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    bin_df = pd.DataFrame(concentrations, columns=bin_mids.astype(str))

    final_df = pd.concat([df["Datetime"], total_df, bin_df], axis=1)

    OPCN = Aerosol2D(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "bin_edges": bin_edges,
        "bin_mids": bin_mids,
        "density": 1.65,
        "serial_number": "unknown",
        "unit": "cm⁻³",
        "dtype": "dN",
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN

#%%

def Load_OPCN3_file_PM_old(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> AerosolAlt:


    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.
    Simpler version, that only returns total concentration and PM1, 2.5 and 10.
    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : Aerosol1D
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")
        
    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"date": "Datetime"}, inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%dT%H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temperature.C": "Temp (C)", "RH.p": "RH (%)",
                 "PM1(ug/m3)": "PM1", "PM2.5(ug/m3)": "PM2.5",
                 "PM10(ug/m3)": "PM10"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df[['Datetime','Temp (C)','RH (%)',"Period (s)"]]

        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    PM_df = df[['PM1','PM2.5','PM10']]

    final_df = pd.concat([df["Datetime"], total_df, PM_df], axis=1)

    OPCN = AerosolAlt(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "density": 1.65,
        "serial_number": "unknown",
        "unit": {"Total_conc": "cm⁻³", "PM": "ug/m³"},
        "dtype": {"Total_conc": "dN", "PM": "dM"},
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN

###############################################################################


def Load_OPCN3_file_PM_new(file: str, extra_data: bool = False,
                        encoding: str = None, delimiter: str = None) -> AerosolAlt:
    """
    Load and format data from a CSV file generated by the OPC-N3 particle sensor.
    Simpler version, that only returns total concentration and PM1, 2.5 and 10.
    Parameters
    ----------
    file : str
        Path to the OPCN3 CSV export file.
    extra_data : bool, optional
        If True, retains non-bin data in `.extra_data` attribute. Default is False.

    Returns
    -------
    OPCN : AerosolAlt
        Object containing:
        - Time-resolved particle number concentrations per bin (in cm⁻³)
        - Metadata including serial number, instrument type, etc.
    """
    if encoding is None and delimiter is None:
        encoding, delimiter = detect_delimiter(file)
    elif encoding is None or delimiter is None:
        raise Exception("Either provide both encoding and delimiter, or neither.")

    df = pd.read_csv(file, delimiter=delimiter, encoding=encoding)
    df.rename(columns={"Date": "Datetime"}, inplace=True)
    df.drop(columns='OPC',inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Parse ISO-formatted timestamp strings (e.g., '2024-01-21T15:30:01.000Z')
    df["Datetime"] = pd.to_datetime(
        df["Datetime"].str.slice(0, 19), format="%Y-%m-%d %H:%M:%S"
    )

    # Determine bin edges/mids
    bin_cols = df.columns[1:25]

    # Correct Period and FlowRate values
    df["Period"] = df["Period"].astype(float) / 100  # seconds
    df["FlowRate"] = df["FlowRate"].astype(float) / 100  # ml/s

    df.rename(
        columns={"Period": "Period (s)", "FlowRate": "FlowRate (ml/s)",
                 "Temp": "Temp (C)", "RH": "RH (%)"}, inplace=True
    )

    # Optional: store extra data
    if extra_data:
        extra_df = df[['Datetime','Temp (C)','RH (%)',"Period (s)"]]
        extra_df.set_index("Datetime", inplace=True)
    else:
        extra_df = pd.DataFrame([])

    # Compute sample volume per row
    sample_volume = df["Period (s)"] * df["FlowRate (ml/s)"]  # in cm³

    # Convert counts to concentrations
    raw_counts = df[bin_cols].astype(float).values
    concentrations = raw_counts / sample_volume.values[:, None]  # #/cm³

    total_conc = np.nansum(concentrations, axis=1)
    total_df = pd.DataFrame(total_conc, columns=["Total_conc"])
    PM_df = df[['PM1','PM2.5','PM10']]
                        
    final_df = pd.concat([df["Datetime"], total_df, PM_df], axis=1)

    OPCN = AerosolAlt(final_df)
    OPCN._meta = {
        "instrument": "OPCN",
        "density": 1.65,
        "serial_number": "unknown",
        "unit": {"Total_conc": "cm⁻³", "PM": "ug/m³"},
        "dtype": {"Total_conc": "dN", "PM": "dM"},
    }

    if extra_data:
        OPCN._extra_data = extra_df
        OPCN._raw_extra_data = extra_df.copy()
    return OPCN