# .readthedocs.yml

version: 2

# Path to your Sphinx configuration file
sphinx:
  configuration: docs/source/conf.py

# Use the latest stable Python version
python:
  version: "3.10"
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

# Optional: tell RTD where to find notebooks or static files if needed
# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.10"
