"""The maintainer's assessment of which Afsnit A entries count as particles.

Afsnit A lists gases, vapours *and* particulate pollution. Entries with a ppm
limit are gases or vapours and are skipped; for the rest, a name giving a
particulate form (dust, powder, fume, mist, a size fraction) or a metal compound
("beregnet som <metal>") includes the entry by rule (see
:mod:`.retsinformation`). This module records the decisions the rules cannot
make, as assessed on 2026-09-27 against BEK nr 613 af 29/06/2026.

The criterion: a limit is only useful here if it is reasonable to assume that
the particles measured *are* that substance — the crude assumption made for,
say, wood dust, where PM is measured and taken to be all wood dust. That rules
out reactive chemicals (NaOH, P₂O₅ …), pesticides, plasticisers and other
industrial organics, chemically defined fractions (PAH, coal-tar pitch), drugs,
and soluble metal compounds whose metal also has a dust entry (soluble Ba and
Tl compounds are the only limits for those metals, so they stay).

Names are compared case-insensitively with the order's own wording. An entry
in neither set that the rules do not include is reported as "needs
assessment", so a substance added by a later order is flagged, not dropped.
"""

from __future__ import annotations

#: Particulate entries whose name alone does not show it.
PARTICLE_NAMES = frozenset(
    {
        "boroxid",
        "calciumhydroxid",
        "calciumoxid",
        "carbon black",
        "emissioner fra dieseludstødning",
        "natriumtetraborat, decahydrat",
        "natriumtetraborat, pentahydrat",
        "natriumtetraborat, vandfri",
        "silicium",
        "vismuttellurid",
        "vismuttellurid, tilsat selen",
    }
)

#: Entries with a mass limit that the measured aerosol would not be assumed to
#: consist of (including some the rules above would otherwise include).
NOT_AEROSOL_NAMES = frozenset(
    {
        "1,2,3,4,5,6-hexachlorcyclohexan, teknisk",
        "1,2,4-benzentricarboxylsyre-1,2-anhydrid",
        "1,3-dichlor-5,5-dimethylhydantoin",
        "1,4-butyndiol",
        "2,4,5-t",
        "2,4,6-trichlorphenol",
        "2,4,6-trinitrophenylmethylnitramin",
        "2,4,6-trinitrotoluen",
        "2,4-d",
        "2,4-dinitrotoluen",
        "2,6-di-tert-butyl-p-cresol",
        "2,6-dinitrotoluen",
        "2-pivaloyl-1,3-indandion",
        "4,4'-methylenbis(2-chloranilin)",
        "4,4'-methylendianilin",
        "4,4'-thiobis(6-tert-butyl-m-cresol)",
        "4-methoxyphenol",
        "acetylsalicylsyre",
        "acrylamid",
        "adipinsyre",
        "aldrin",
        "aluminium, opløselige salte, beregnet som al",
        "amitrol",
        "ammoniumperfluoroctanoat",
        "ammoniumsulfamat",
        "antu",
        "atrazin",
        "azinphosmethyl",
        "benomyl",
        "benzoylperoxid",
        "benzylbutylphthalat",
        "bromacil",
        "calciumcyanamid",
        "camphechlor",
        "captafol",
        "captan",
        "carbaryl",
        "carbofuran",
        "chlordan",
        "chlorphenol og salte heraf, beregnet som",
        "chlorpyrifos",
        "clopidol",
        "crufomat",
        "cyanider, alkalimetal, beregnet som cn",
        "cæsiumhydroxid",
        "ddt",
        "di(2-ethylhexyl)phthalat",
        "diallylphthalat",
        "diazinon",
        "dibenzylphthalat",
        "dibrom",
        "dibutylphthalat",
        "dicrotophos",
        "dicyclohexylphthalat",
        "dieldrin",
        "diethylphthalat",
        "diisobutylphthalat",
        "diisocyanater",
        "diisodecylphthalat",
        "diisononylphthalat",
        "diisooctylphthalat",
        "dimethylphthalat",
        "dinitro-o-cresol",
        "dinitrotoluen, alle isomere",
        "dioxathion",
        "diphenylamin",
        "diquat, respirabel",
        "diquat, totalstøv",
        "disul",
        "disulfiram",
        "disyston",
        "diuron",
        "endosulfan",
        "endrin",
        "epn",
        "ethion",
        "fenamiphos",
        "fenthion",
        "ferbam",
        "fluorider, undtagen de andetsteds i listen nævnte, beregnet som f",
        "fonofos",
        "heptachlor",
        "hexachlorbenzen",
        "hexachlornaphthalen",
        "hydroquinon",
        "jernsalte, opløselige, beregnet som fe",
        "kaliumhydroxid",
        "lindan",
        "lithiumhydrid",
        "lithiumhydrid, inhalerbar",
        "m-phenylendiamin",
        "m-phthalodinitril",
        "malathion",
        "methomyl",
        "methoxychlor",
        "methylethylketonperoxid",
        "metribuzin",
        "molybdænforbindelser, opløselige, beregnet som mo",
        "monocrotophos",
        "natriumazid",
        "natriumfluoracetat",
        "natriumhydrogensulfit",
        "natriumhydroxid",
        "natriumpyrithion",
        "natriumpyrosulfit",
        "nicotin",
        "niobiumforbindelser, opløselige, beregnet som nb",
        "o-phenylendiamin",
        "octachlornaphthalen",
        "oxalsyre",
        "p-phenylendiamin",
        "paraquat",
        "parathion",
        "parathionmethyl",
        "pentachlornaphthalen",
        "pentachlornitrobenzen",
        "persulfater, alkalimetal, beregnet som s₂o₈",
        "phenothiazin",
        "phorat",
        "phosphor, gult",
        "phosphorpentachlorid",
        "phosphorpentaoxid",
        "phosphorpentasulfid",
        "phosphorsyre",
        "phtalater (estere), der ikke er nævnt andet sted i listen",
        "phthalsyreanhydrid",
        "picloram",
        "picrinsyre",
        "piperazin og salte heraf, beregnet som piperazin, se dog piperazindihydrochlorid",
        "piperazindihydrochlorid",
        "platinforbindelser, opløselige, beregnet som pt",
        "plictran",
        "polyaromatiske carbonhydrider (partikulære, benzenopløselig fraktion)",
        "polychlorerede biphenyler",
        "polyethylenglycol (peg) med middelmolvægt på 200-600",
        "propoxur",
        "pyrethrum",
        "rdx",
        "rhodiumforbindelser, opløselige, beregnet som rh",
        "ronnel",
        "rotenon",
        "stenkulstjærebeg, flygtige bestanddele, benzenopløselig fraktion",
        "stryknin",
        "subtilisiner",
        "sulfometuron-methyl",
        "sulprofos",
        "svovlsyre, tåge, thorakal fraktion",
        "terephthalsyre",
        "tetrachlornaphthalen",
        "tetranatriumpyrophosphat",
        "thiram",
        "tinforbindelser, organiske, beregnet som sn, se dog tri-n-butyltinforbindelser",
        "tri-o-cresylphosphat",
        "trichloreddikesyre",
        "trichlornaphthalen",
        "trichlorphenol og salte heraf, beregnet som",
        "triphenylamin",
        "triphenylphosphat",
        "warfarin",
        "wolframforbindelser, opløselige, beregnet som w",
    }
)
